const images = {
  appLogo: require('./images/appIcon.png'),
  userIcon: require('./images/user_icon.png'),
  greenLockIcon: require('./images/green_lock.png'),
  dropdownIcon: require('./images/chevron_down.png'),
  cancelIcon: require('./images/cancel.png'),
  menuIcon: require('./images/menuIcon1.png'),
  mailIcon: require('./images/mail_Icon.png'),
  phoneIcon: require('./images/phoneIcon.png'),
  eyeIcon: require('./images/eye_icon.png'),
  closeEyeIcon: require('./images/eye_close.png'),
  dashboardIcon: require('./images/dashboard.png'),
  aboutIcon: require('./images/about.png'),
  settingIcon: require('./images/setting.png'),
  backIcon: require('./images/back_icon.png'),
  galleryIcon: require('./images/galleryIcon.png'),
  documentIcon: require('./images/document.png'),
  applicantIcon: require('./images/applicantIcon3.png'),
  planeIcon: require('./images/planePaper.png'),
  darkPlaneIcon: require('./images/darkPlane.png'),
  applicantFormIcon: require('./images/applicant.png'),
  groupIcon: require('./images/groupIcon.png'),
  grtIcon: require('./images/grtIcon.png'),
  cameraIcon: require('./images/camera.png'),
  cameraIcon1: require('./images/camera1.png'),
  applicantScreen: require('./images/loanScreen.png'),
  grtScreen: require('./images/grtScreen.png'),
  whiteBack: require('./images/white_Back.png'),
  successIcon: require('./images/successIcon.png'),
  cancelRedIcon: require('./images/cancelIcon.png'),
  checkBoxIcon: require('./images/checkBox.png'),
  loanIcon: require('./images/loanApp.png'),
};

export {images};
