import R from '../res/R';

const AppContent = {
  roleList: [
    'Engineer',
    'Machanic',
    'Doctor',
    'Driver',
    'Influencer',
    'Businessman',
    'ShopKeeper',
  ],
  genderList: [
    {
      id: '1',
      RoleName: 'Male',
    },
    {
      id: '2',
      RoleName: 'Female',
    },
    {
      id: '3',
      RoleName: 'Other',
    },
  ],
  maritalStatusList: [
    {
      id: '1',
      RoleName: 'Married',
    },
    {
      id: '2',
      RoleName: 'Unmarried',
    },
  ],

  memberQualification: [
    {
      id: '1',
      RoleName: 'HSC',
    },
    {
      id: '2',
      RoleName: 'SSC',
    },
    {
      id: '3',
      RoleName: 'Graduation',
    },
    {
      id: '4',
      RoleName: 'Post Graduation',
    },
    {
      id: '5',
      RoleName: 'Other Degree',
    },
  ],

  religionList: [
    {
      id: '1',
      RoleName: 'Hindu',
    },
    {
      id: '2',
      RoleName: 'Buddha',
    },
    {
      id: '3',
      RoleName: 'Islam',
    },
    {
      id: '4',
      RoleName: 'Sikhism',
    },
    {
      id: '5',
      RoleName: 'Other',
    },
  ],

  casteList: [
    {
      id: '1',
      RoleName: 'Genral',
    },
    {
      id: '2',
      RoleName: 'OBC',
    },
    {
      id: '3',
      RoleName: 'SC/ST',
    },
    {
      id: '4',
      RoleName: 'Other',
    },
  ],
  houseStatusList: [
    {
      id: '1',
      RoleName: 'houseStatus1',
    },
    {
      id: '2',
      RoleName: 'houseStatus12',
    },
    {
      id: '3',
      RoleName: 'houseStatus13',
    },
    {
      id: '4',
      RoleName: 'houseStatus14',
    },
  ],
  natureBusinessList: [
    {
      id: '1',
      RoleName: 'natureBusiness',
    },
    {
      id: '2',
      RoleName: 'natureBusiness2',
    },
    {
      id: '3',
      RoleName: 'natureBusiness3',
    },
    {
      id: '4',
      RoleName: 'natureBusiness4',
    },
  ],

  noOfMember: [
    {
      id: '1',
      RoleName: '1',
    },
    {
      id: '2',
      RoleName: '2',
    },
    {
      id: '3',
      RoleName: '3',
    },
    {
      id: '4',
      RoleName: '4',
    },
  ],
  NomanidataList: [
    {
      id: '1',
      RoleName: 'Father',
    },
    {
      id: '2',
      RoleName: 'Mother',
    },
    {
      id: '3',
      RoleName: 'Brother',
    },
    {
      id: '4',
      RoleName: 'Sister',
    },
    {
      id: '5',
      RoleName: 'GrandFather',
    },
    {
      id: '6',
      RoleName: 'GrandMother',
    },
    {
      id: '7',
      RoleName: 'Uncle',
    },
  ],
  accountType: [
    {
      id: '1',
      RoleName: 'Saving',
    },
    {
      id: '2',
      RoleName: 'Current',
    },
    {
      id: '3',
      RoleName: 'Saving',
    },
  ],

  LoanProposalHeader: [
    {
      id: '1',
      title: 'Income Details',
    },
    {
      id: '2',
      title: 'Monthly Expenses',
    },
    {
      id: '3',
      title: 'Loan Proposal',
    },
  ],

  ApprovedStatusGrt: [
    {
      id: 1,
      approvedTitile: 'Accept',
    },
    {
      id: 0,
      approvedTitile: 'Rejected',
    },
  ],

  HeaderCardList: [
    {
      id: '1',
      title: 'Applicant',
      subTitle: 'Report',
      url: 'https://cdn-icons-png.flaticon.com/128/3534/3534066.png',
      firstColor: '#6DD4CE',
      secondColor: R.colors.appColor,
      thirdColor: '#025A56',
      // firstColor: '#92d3f9',
      // secondColor: '#015485',
    },
    {
      id: '2',
      title: 'Branch',
      subTitle: 'Report',
      url: 'https://cdn-icons-png.flaticon.com/128/4435/4435114.png',
      // firstColor: '#6DD4CE',
      // secondColor: R.colors.appColor,
      // thirdColor: '#025A56',
      firstColor: '#92d3f9',
      secondColor: '#1973A8',
      thirdColor: '#015485',
    },
    {
      id: '3',
      title: 'Collection',
      subTitle: 'Report',
      url: 'https://cdn-icons-png.flaticon.com/128/4137/4137098.png',
      // firstColor: '#6DD4CE',
      // secondColor: R.colors.appColor,
      // thirdColor: '#025A56',
      firstColor: '#92d3f9',
      secondColor: '#1973A8',
      thirdColor: '#015485',
    },
    {
      id: '4',
      title: 'Performance',
      subTitle: 'Report',
      url: 'https://cdn-icons-png.flaticon.com/128/11200/11200751.png',
      firstColor: '#6DD4CE',
      secondColor: R.colors.appColor,
      thirdColor: '#025A56',
      // firstColor: '#Fbc576',
      // secondColor: '#E49A2E',
      // thirdColor: '#C57703',
    },
  ],

  LoanCardList: [
    {
      id: 0,
      Title: 'Loan',
      subTitle: 'Application',
      icon: 'https://cdn-icons-png.flaticon.com/128/9196/9196974.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/9196/9196725.png',
      icon1: R.images.loanIcon,
      Url: 'ApplicantForm',
      For: 'LoanApplication',
      firstColor: '#69e2dc',
      secondColor: '#1a918b',
      thirdColor: '#01635e',
    },
    {
      id: 1,
      Title: 'Group',
      subTitle: 'Formation',
      icon: 'https://cdn-icons-png.flaticon.com/128/1239/1239719.png',
      icon1: R.images.groupIcon,
      Url: 'GroupForm',
      For: 'GroupForm',
      firstColor: '#92d3f9',
      secondColor: '#1973A8',
      thirdColor: '#015485',
    },
    {
      id: 2,
      Title: 'Center',
      subTitle: 'Formation',
      icon: 'https://cdn-icons-png.flaticon.com/128/1321/1321898.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/5718/5718761.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/8572/8572066.png',
      icon1: R.images.applicantFormIcon,
      Url: 'CenterForm',
      For: 'CenterForm',
      firstColor: '#F99c92',
      secondColor: '#bf2c1b',
      thirdColor: '#901102',
    },
    {
      id: 3,
      Title: 'GRT',
      subTitle: 'Formation',
      icon: 'https://cdn-icons-png.flaticon.com/128/3258/3258583.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/10063/10063899.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/12626/12626809.png',
      icon1: R.images.grtScreen,
      Url: 'GrtForm',
      For: 'Grt',
      firstColor: '#Fbc576',
      secondColor: '#E49A2E',
      thirdColor: '#C57703',
    },
    {
      id: 4,
      Title: 'Loan',
      subTitle: 'Proposal',
      icon: 'https://cdn-icons-png.flaticon.com/128/2683/2683317.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/649/649622.png',
      icon1: R.images.applicantFormIcon,
      Url: 'LoanProposal',
      For: 'LoanProposal',
      firstColor: '#C9C9C9',
      secondColor: '#676967',
      thirdColor: '#242524',
    },
    {
      id: 5,
      Title: 'Loan',
      subTitle: 'Approval',
      // icon: 'https://cdn-icons-png.flaticon.com/128/3188/3188129.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/5336/5336612.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/12693/12693762.png',
      icon: 'https://cdn-icons-png.flaticon.com/128/4957/4957835.png',
      icon1: R.images.applicantFormIcon,
      Url: 'LoanApproval',
      For: 'LoanApproval',
      firstColor: '#e8d9fa',
      secondColor: '#7a3fbf',
      thirdColor: '#280256',
    },
    {
      id: 6,
      Title: 'Pre ',
      subTitle: 'Disbursement',
      icon: 'https://cdn-icons-png.flaticon.com/128/781/781760.png',
      icon1: R.images.applicantFormIcon,
      Url: 'DisbursementScreen',
      For: 'DisbursementScreen',
      firstColor: '#F7AF71',
      secondColor: '#F77408',
      thirdColor: '#A64e02',
    },
    {
      id: 7,
      Title: 'Payment',
      subTitle: 'Collection',
      icon: 'https://cdn-icons-png.flaticon.com/128/4108/4108843.png',
      icon1: R.images.applicantFormIcon,
      Url: 'PaymentScreen',
      For: 'PaymentScreen',
      firstColor: '#ADEBFB',
      secondColor: '#1598B9',
      thirdColor: '#027A98',
    },
  ],
  BROLoanCardList: [
    {
      id: 0,
      Title: 'Loan',
      subTitle: 'Application',
      icon: 'https://cdn-icons-png.flaticon.com/128/9196/9196974.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/9196/9196725.png',
      icon1: R.images.loanIcon,
      Url: 'ApplicantForm',
      For: 'LoanApplication',
      firstColor: '#69e2dc',
      secondColor: '#1a918b',
      thirdColor: '#01635e',
    },
    {
      id: 1,
      Title: 'Group',
      subTitle: 'Formation',
      icon: 'https://cdn-icons-png.flaticon.com/128/1239/1239719.png',
      icon1: R.images.groupIcon,
      Url: 'GroupForm',
      For: 'GroupForm',
      firstColor: '#92d3f9',
      secondColor: '#1973A8',
      thirdColor: '#015485',
    },
    {
      id: 2,
      Title: 'Center',
      subTitle: 'Formation',
      icon: 'https://cdn-icons-png.flaticon.com/128/1321/1321898.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/5718/5718761.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/8572/8572066.png',
      icon1: R.images.applicantFormIcon,
      Url: 'CenterForm',
      For: 'CenterForm',
      firstColor: '#F99c92',
      secondColor: '#bf2c1b',
      thirdColor: '#901102',
    },
    {
      id: 3,
      Title: 'Loan',
      subTitle: 'Proposal',
      icon: 'https://cdn-icons-png.flaticon.com/128/2683/2683317.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/649/649622.png',
      icon1: R.images.applicantFormIcon,
      Url: 'LoanProposal',
      For: 'LoanProposal',
      firstColor: '#F7AF71',
      secondColor: '#F77408',
      thirdColor: '#A64e02',
    },
    {
      id: 4,
      Title: 'Payment',
      subTitle: 'Collection',
      icon: 'https://cdn-icons-png.flaticon.com/128/4108/4108843.png',
      icon1: R.images.applicantFormIcon,
      Url: 'PaymentScreen',
      For: 'PaymentScreen',
      firstColor: '#ADEBFB',
      secondColor: '#1598B9',
      thirdColor: '#027A98',
    },
  ],
  ManagerLoanCardList: [
    {
      id: 0,
      Title: 'GRT',
      subTitle: 'Formation',
      icon: 'https://cdn-icons-png.flaticon.com/128/3258/3258583.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/10063/10063899.png',
      // icon: 'https://cdn-icons-png.flaticon.com/128/12626/12626809.png',
      icon1: R.images.grtScreen,
      Url: 'GrtForm',
      For: 'Grt',
      firstColor: '#Fbc576',
      secondColor: '#E49A2E',
      thirdColor: '#C57703',
    },
    {
      id: 1,
      Title: 'Loan',
      subTitle: 'Approval',
      icon: 'https://cdn-icons-png.flaticon.com/128/3188/3188129.png',
      icon1: R.images.applicantFormIcon,
      Url: 'LoanApproval',
      For: 'LoanApproval',
      firstColor: '#92d3f9',
      secondColor: '#1973A8',
      thirdColor: '#015485',
    },
    {
      id: 2,
      Title: 'Pre ',
      subTitle: 'Disbursement',
      icon: 'https://cdn-icons-png.flaticon.com/128/781/781760.png',
      icon1: R.images.applicantFormIcon,
      Url: 'DisbursementScreen',
      For: 'DisbursementScreen',
      firstColor: '#69e2dc',
      secondColor: '#1a918b',
      thirdColor: '#01635e',
    },
  ],
};

export default AppContent;
